/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUMNOS
 */
public class FrmProveedor extends javax.swing.JFrame {
 private static Connection conn;
    /**
     * Creates new form FmrCliente
     */
    public FrmProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
      void posicion(){
    this.setSize(716,400);
        this.setMinimumSize(new Dimension(716,400));
        this.setLocationRelativeTo(null); 
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROVEEDOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE PROVEEDORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 241, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID_PROVEEDOR:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 21));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RAZON SOCIAL:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 21));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DIRECCION:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 80, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELEFONO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 30));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, 30));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, 33));

        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 250, 30));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 183, 32));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/search.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 121, -1));

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/insertar.png"))); // NOI18N
        btn_nuevo.setText("AGREGAR");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/save.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/actualizar.png"))); // NOI18N
        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/elimina.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/regresar.png"))); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CI/RUC:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 60, 20));
        getContentPane().add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla (8).png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        nuevo();
        txt_id.requestFocus();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
if (txt_nombre.getText().equals("")
        || txt_ruc.getText().equals("")
    || txt_direccion.getText().equals("")
      || txt_telefono.getText().equals("")){
    JOptionPane. showMessageDialog(null,
            "Los campos no pueden estar vacios ", "Mensaje del sistema",
            JOptionPane.ERROR_MESSAGE);
    
}else{
    guardar();
    txt_nombre.requestFocus();
    nuevo();
}     
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if(txt_nombre.getText().equals("") ||
                txt_direccion.getText().equals("")
                || txt_ruc.getText().equals("")
                ||txt_telefono.getText().equals("")
                ||txt_id.getText().equals("")|| txt_id.getText() == "0" ){
            JOptionPane.showMessageDialog(null,
                    "Los campos no pueden estar vacios","Mensaje del Sistema",
                   JOptionPane.ERROR_MESSAGE);
        }else{
            modificar();
            txt_id.requestFocus();
            nuevo();
        }
                
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if(txt_nombre.getText().equals("")|| txt_direccion.getText().equals("")
               || txt_ruc.getText().equals("")
        ||txt_telefono.getText().equals("")
        ||txt_id.getText().equals("")
          ||txt_id.getText() =="0") {
           JOptionPane.showMessageDialog(null,"Los campos no pueden estar vacios ",
                   "Mensaje del sistema ",
           JOptionPane.ERROR_MESSAGE);
       } else{
           eliminar();
           txt_id.requestFocus();
           nuevo();
       }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (txt_id.getText().equals("")|| txt_id.getText ()=="0") {
            JOptionPane.showMessageDialog(null,
                    "ingrese un id existente", "mensaje del sistema",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            buscar();
            txt_id.requestFocus();
        }
                
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      MenuPrinc obj = new MenuPrinc();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private void nuevo() {
        txt_id.setText("");
        txt_nombre.setText("");
         txt_ruc.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
    }

    private void guardar() {
      if (Conexion.conectar()){
          String sql= "INSERT into Proveedor(id_prov,nombre_prov,ruc_prov,direccion_prov,telefono_prov)"
                  + "VALUES ('" + Integer.parseInt(txt_id.getText())  + "','"
                  +txt_nombre.getText() + "','"
                   +txt_ruc.getText() + "','"
                  +txt_direccion.getText() +" ','"
                  +txt_telefono.getText() +" ')";
          try{
              Conexion.getSt().executeUpdate(sql);
              JOptionPane.showMessageDialog(null,"Registro guardado ",
                      "Mensaje del Sistema",
                      JOptionPane.INFORMATION_MESSAGE);
              
          }catch (SQLException ex) {
              Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE,null,ex);
          }
      }
    }

    private void modificar() {
    if(Conexion.conectar()){
        String sql = "UPDATE proveedor SET nombre_prov='" + txt_nombre.getText () + "',"
                +"ruc_prov='" + txt_ruc.getText() +  "',"
        +"direccion_prov='" + txt_direccion.getText() +  "',"
        +"telefono_prov='" + txt_telefono.getText() + "' "
        +"where id_prov=" + Integer.parseInt(txt_id.getText());
        try{
            Conexion.getSt().executeUpdate (sql);
            JOptionPane.showMessageDialog(null,"Registro Modificado","Mensaje del Sistema ",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()). log(Level.SEVERE, null, ex);   
        }
    }    
    }

    private void eliminar() {
     if(Conexion.conectar()){
        String sql = "delete from proveedor where "
                + "id_cliente='"+Integer.parseInt(txt_id.getText())+"'";
        try{
            Conexion.getSt().executeUpdate (sql);
            JOptionPane.showMessageDialog(null,"registro eliminado  ",
                    "mensaje del sistema",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE,
                    null, ex);
        }
    }   
    }

    private void buscar() {
    if(Conexion.conectar()){
        String sql= "select * from proveedor where id_prov='" + Integer.parseInt(txt_id.getText ())+"'";
        try{
            ResultSet rs = Conexion. getSt (). executeQuery (sql);
            if (rs.next()) {// si existe tomo los datos y los guardo dentro de usuario)
                    txt_nombre.setText(rs.getString("nombre_prov"));
                     txt_ruc.setText(rs.getString("ruc_prov"));
            txt_direccion.setText(rs.getString("direccion_prov"));
                    txt_telefono.setText(rs.getString("telefono_prov"));
            }else{
                txt_id.setText("0");
                txt_nombre.setText("");
                txt_ruc.setText("");
                txt_direccion.setText("");
                txt_telefono.setText("");
                JOptionPane.showMessageDialog(null, " El registro no existe", "Mensaje del sistema",
                        JOptionPane.ERROR_MESSAGE);
            }         
        }catch (SQLException ex) {
            Logger.getLogger (FrmProveedor.class.getName()).log(Level.SEVERE,null,ex);
        }
            
    }    
    }
}
