/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Dimension;

/**
 *
 * @author Antony_99
 */
public class MenuPrinc extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrinc
     */
    public MenuPrinc() {
        initComponents();
         this.setLocationRelativeTo(null);
    }
     void posicion(){
    this.setSize(710,560);
        
        this.setLocationRelativeTo(null); 
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        MenuPrinc = new javax.swing.JMenuBar();
        REGISTRAR = new javax.swing.JMenu();
        sub_cliente = new javax.swing.JMenuItem();
        sub_proveedor = new javax.swing.JMenuItem();
        CATEGORIA = new javax.swing.JMenu();
        sub_platos = new javax.swing.JMenuItem();
        sub_postres = new javax.swing.JMenuItem();
        sub_bebidas = new javax.swing.JMenuItem();
        PEDIDOS = new javax.swing.JMenu();
        sub_nuevo = new javax.swing.JMenuItem();
        CONSULTAS = new javax.swing.JMenu();
        c_platos = new javax.swing.JMenuItem();
        c_bebidas = new javax.swing.JMenuItem();
        c_postres = new javax.swing.JMenuItem();
        c_cliente = new javax.swing.JMenuItem();
        c_proveedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        SALIR = new javax.swing.JMenu();
        sub_cerrar = new javax.swing.JMenuItem();
        sub_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL - RESTAURANTE PARIS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setDoubleBuffered(true);
        Escritorio.setFocusCycleRoot(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/Captura de pantalla (16).png"))); // NOI18N
        Escritorio.add(jLabel1);
        jLabel1.setBounds(0, 0, 716, 520);

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        MenuPrinc.setBackground(new java.awt.Color(255, 255, 255));
        MenuPrinc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 98, 111)));
        MenuPrinc.setForeground(new java.awt.Color(43, 98, 111));
        MenuPrinc.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        REGISTRAR.setBackground(new java.awt.Color(0, 153, 153));
        REGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/Folder - MSN M Chatlogs.png"))); // NOI18N
        REGISTRAR.setText("REGISTRAR");

        sub_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        sub_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/community_users_12977.png"))); // NOI18N
        sub_cliente.setText("CLIENTES");
        sub_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_clienteActionPerformed(evt);
            }
        });
        REGISTRAR.add(sub_cliente);

        sub_proveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        sub_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/42554deliverytruck_98967.png"))); // NOI18N
        sub_proveedor.setText("PROVEEDORES");
        sub_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_proveedorActionPerformed(evt);
            }
        });
        REGISTRAR.add(sub_proveedor);

        MenuPrinc.add(REGISTRAR);

        CATEGORIA.setBackground(new java.awt.Color(255, 255, 255));
        CATEGORIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/3592870-brochure-document-menu-note-office-page-papers_107750.png"))); // NOI18N
        CATEGORIA.setText("CATEGORIA");

        sub_platos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        sub_platos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/Dish_Pasta_Spaghetti_26373.png"))); // NOI18N
        sub_platos.setText("PLATOS");
        sub_platos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_platosActionPerformed(evt);
            }
        });
        CATEGORIA.add(sub_platos);

        sub_postres.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        sub_postres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/recipedessertcakeicon_109876.png"))); // NOI18N
        sub_postres.setText("POSTRES");
        sub_postres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_postresActionPerformed(evt);
            }
        });
        CATEGORIA.add(sub_postres);

        sub_bebidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        sub_bebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/Alcohol_Brandy_26377.png"))); // NOI18N
        sub_bebidas.setText("BEBIDAS");
        sub_bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_bebidasActionPerformed(evt);
            }
        });
        CATEGORIA.add(sub_bebidas);

        MenuPrinc.add(CATEGORIA);

        PEDIDOS.setBackground(new java.awt.Color(255, 255, 255));
        PEDIDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/checklist_25365.png"))); // NOI18N
        PEDIDOS.setText("PEDIDOS");

        sub_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        sub_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/insertar.png"))); // NOI18N
        sub_nuevo.setText("Nuevo");
        sub_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_nuevoActionPerformed(evt);
            }
        });
        PEDIDOS.add(sub_nuevo);

        MenuPrinc.add(PEDIDOS);

        CONSULTAS.setBackground(new java.awt.Color(255, 255, 255));
        CONSULTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/report256_24829.png"))); // NOI18N
        CONSULTAS.setText("CONSULTAS");

        c_platos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        c_platos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/Dish_Pasta_Spaghetti_26373.png"))); // NOI18N
        c_platos.setText("PLATOS");
        c_platos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_platosActionPerformed(evt);
            }
        });
        CONSULTAS.add(c_platos);

        c_bebidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        c_bebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/Alcohol_Brandy_26377.png"))); // NOI18N
        c_bebidas.setText("BEBIDAS");
        c_bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_bebidasActionPerformed(evt);
            }
        });
        CONSULTAS.add(c_bebidas);

        c_postres.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        c_postres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/recipedessertcakeicon_109876.png"))); // NOI18N
        c_postres.setText("POSTRES");
        c_postres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_postresActionPerformed(evt);
            }
        });
        CONSULTAS.add(c_postres);

        c_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        c_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/community_users_12977.png"))); // NOI18N
        c_cliente.setText("CLIENTES");
        c_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_clienteActionPerformed(evt);
            }
        });
        CONSULTAS.add(c_cliente);

        c_proveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        c_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sub/42554deliverytruck_98967.png"))); // NOI18N
        c_proveedor.setText("PROVEEDORES");
        c_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_proveedorActionPerformed(evt);
            }
        });
        CONSULTAS.add(c_proveedor);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/lista.png"))); // NOI18N
        jMenuItem1.setText("FACTURAS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        CONSULTAS.add(jMenuItem1);

        MenuPrinc.add(CONSULTAS);

        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu/play-button_icon-icons.com_60615.png"))); // NOI18N
        SALIR.setText("SALIR");

        sub_cerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        sub_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/key_1564.png"))); // NOI18N
        sub_cerrar.setText("Cerrar Sesión");
        sub_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_cerrarActionPerformed(evt);
            }
        });
        SALIR.add(sub_cerrar);

        sub_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sub_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/salir.png"))); // NOI18N
        sub_salir.setText("Salir");
        sub_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_salirActionPerformed(evt);
            }
        });
        SALIR.add(sub_salir);

        MenuPrinc.add(SALIR);

        setJMenuBar(MenuPrinc);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_clienteActionPerformed
    new FrmCliente().setVisible(true); 
    }//GEN-LAST:event_sub_clienteActionPerformed

    private void sub_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_proveedorActionPerformed
     new FrmProveedor().setVisible(true); 
    }//GEN-LAST:event_sub_proveedorActionPerformed

    private void sub_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_salirActionPerformed
this.dispose();
    }//GEN-LAST:event_sub_salirActionPerformed

    private void sub_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_cerrarActionPerformed
  Login principal= new Login();
    principal.setVisible(true);
    principal.pack();
       this.setVisible(false);
    }//GEN-LAST:event_sub_cerrarActionPerformed

    private void sub_platosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_platosActionPerformed
PedidoPlato cli = new PedidoPlato();
    
    cli.toFront();
    cli.setVisible(true);
//    new PedidoPlato().setVisible(true); 
    }//GEN-LAST:event_sub_platosActionPerformed

    private void sub_bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_bebidasActionPerformed
    new PedidoBebida().setVisible(true);
    }//GEN-LAST:event_sub_bebidasActionPerformed

    private void sub_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_nuevoActionPerformed
 Factura fac= new Factura();
    Escritorio.add(fac);
    fac.show();    
//new Factura().setVisible(true);
    }//GEN-LAST:event_sub_nuevoActionPerformed

    private void sub_postresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_postresActionPerformed
    new PedidoPostre().setVisible(true);
    }//GEN-LAST:event_sub_postresActionPerformed

    private void c_platosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_platosActionPerformed
new Consul_Plato().setVisible(true);  
    }//GEN-LAST:event_c_platosActionPerformed

    private void c_bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_bebidasActionPerformed
new Consul_Bebida().setVisible(true);
    }//GEN-LAST:event_c_bebidasActionPerformed

    private void c_postresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_postresActionPerformed
  new Consul_Postre().setVisible(true);
    }//GEN-LAST:event_c_postresActionPerformed

    private void c_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_clienteActionPerformed
new Consul_Cliente().setVisible(true);
    }//GEN-LAST:event_c_clienteActionPerformed

    private void c_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_proveedorActionPerformed
     new Consul_Proveedor().setVisible(true);
    }//GEN-LAST:event_c_proveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  
   ConsultasFacturas det= new ConsultasFacturas();
    Escritorio.add(det);
    det.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu CATEGORIA;
    private javax.swing.JMenu CONSULTAS;
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar MenuPrinc;
    private javax.swing.JMenu PEDIDOS;
    public javax.swing.JMenu REGISTRAR;
    private javax.swing.JMenu SALIR;
    private javax.swing.JMenuItem c_bebidas;
    private javax.swing.JMenuItem c_cliente;
    private javax.swing.JMenuItem c_platos;
    private javax.swing.JMenuItem c_postres;
    private javax.swing.JMenuItem c_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem sub_bebidas;
    private javax.swing.JMenuItem sub_cerrar;
    private javax.swing.JMenuItem sub_cliente;
    private javax.swing.JMenuItem sub_nuevo;
    private javax.swing.JMenuItem sub_platos;
    private javax.swing.JMenuItem sub_postres;
    private javax.swing.JMenuItem sub_proveedor;
    private javax.swing.JMenuItem sub_salir;
    // End of variables declaration//GEN-END:variables
}
